### ISSUE TITLE
[WIP] Build and publish ppc64le container images to quay.io

### ISSUE THREAD

**Issue by seth-priya** [razee-io/RemoteResourceS3#164]
**Is your feature request related to a problem? Please describe.**
Community provided container images are currently available for amd64 but not for ppc64le in quay.io

**Describe the solution you'd like**
Build and publish ppc64le images (via travis-ci?) to quay.io

**Describe alternatives you've considered**
Build the images locally on OCP 4.5 cluster

**Additional context**
The build and all automated tests pass on RHEL 8.2, ppc64le , last few lines of the logs for reference

  bunyan-api
    #createLogger()
      ✓ should create logger with specified env var LOG_LEVEL=warn (40) (717ms)
      ✓ should create logger with log level info(30) when no LOG_LEVEL specified
      ✓ should create logger with log level info(30) when unknown LOG_LEVEL specified

  3 passing (740ms)

--------------------------------|---------|----------|---------|---------|-------------------
File                            | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s
--------------------------------|---------|----------|---------|---------|-------------------
All files                       |    2.84 |     8.33 |    7.69 |    2.87 |
 RemoteResourceS3               |       0 |      100 |     100 |       0 |
  main.js                       |       0 |      100 |     100 |       0 | 17-19
 RemoteResourceS3/src           |    2.87 |     8.33 |    7.69 |    2.91 |
  RemoteResourceS3Controller.js |       0 |        0 |       0 |       0 | 17-226
  bunyan-api.js                 |     100 |      100 |     100 |     100 |
  index.js                      |       0 |        0 |       0 |       0 | 17-55
--------------------------------|---------|----------|---------|---------|-------------------

**Comment by seth-priya** [comment]
The image can be built successfully as well and the pod runs successfully on OCP 4.5 as part of RHM deployment, last few lines of the log
STEP 9: FROM node:lts-alpine
STEP 10: USER node
--> Using cache e52085f6cc15f974db0185c49cc311912f948c93c47a9d4fb1dc5dd57411630a
STEP 11: WORKDIR /home/node
--> Using cache 6005e23e8eec0ae8831134a5f53dec74d7b72da0cd86e6dca7cac76eb76ed384
STEP 12: COPY --chown=node --from=buildImg /home/node /home/node
--> f8d82bfa499
STEP 13: CMD ["npm", "start"]
STEP 14: COMMIT remoteresources3
--> dc3a201a803
dc3a201a8035a28a898d42971716a07ea16c3f74b8941c6e47650fb2d62c8087

rhm-remoteresources3-controller-7f66888586-vqq9t   1/1     Running            0          5d23h

**Comment by seth-priya** [comment]
So I did manage run this on travis for ppc64le as well, but there is one caveat

The "npm run lint" command fails because "shellcheck" which is invoked as part of it does not have ppc64le support. I have looked into it and created an issue in the community for Power support https://github.com/koalaman/shellcheck/issues/1767

**Comment by seth-priya** [comment]
The job passes with shellcheck disabled (so everything else is good)
https://travis-ci.org/github/seth-priya/RemoteResourceS3/jobs/740147485
with the following changes
https://github.com/seth-priya/RemoteResourceS3/commit/6647651d8c286fe042357b65c55cf21b7fd9af1d

**Comment by alewitt2** [comment]
https://github.com/razee-io/RemoteResourceS3/pull/179
