### ISSUE TITLE
problem with token caching feature

### ISSUE THREAD

**Issue by daniel-grover** [razee-io/RemoteResourceS3#281]
**Describe the bug**
writing out of token to pod's file system doesn't seem to clear out the previous token.  If the new token is shorter than the previous token the file will contain invalid json preventing the file from being read back in.

**To Reproduce**
1. run the remote resource s3 controller
2. use IAM as the access mechanism
3. let run, it will eventually fail 

**Expected behavior**
It is expected that the token caching continues to work

**Kubernetes Version (kubectl version):**
 - Client: 1.22
 - Server: 1.19

**Additional context**
---
    ~ $ cat ./download-cache/s3token-cache/a5249f8c1c5ee37b96b7d421b4163945d69490cdc4cbe09fd8fc2554138c38ad.json
    {"access_token":"eyJraWQiOiIyMDIxMTExNzA4MjAiLCJhbGciOiJSUzI1NiJ9.eyJpYW1faWQiOiJpYW0tU2VydmljZUlkLWU5OWM5OTdlLWU3OTctNDA2Mi1hNDY0LTU4YWM3MDQ4NTllZSIsImlkIjoiaWFtLVNlcnZpY2VJZC1lOTljOTk3ZS1lNzk3LTQwNjItYTQ2NC01OGFjNzA0ODU5ZWUiLCJyZWFsbWlkIjoiaWFtIiwianRpIjoiZGQ4ZTJmMzctYTVlYS00ZDhlLWJkYjItYzc0OTIyNzM4OWRjIiwiaWRlbnRpZmllciI6IlNlcnZpY2VJZC1lOTljOTk3ZS1lNzk3LTQwNjItYTQ2NC01OGFjNzA0ODU5ZWUiLCJuYW1lIjoiY29zLWFwaS1rZXkiLCJzdWIiOiJTZXJ2aWNlSWQtZTk5Yzk5N2UtZTc5Ny00MDYyLWE0NjQtNThhYzcwNDg1OWVlIiwic3ViX3R5cGUiOiJTZXJ2aWNlSWQiLCJhdXRobiI6eyJzdWIiOiJTZXJ2aWNlSWQtZTk5Yzk5N2UtZTc5Ny00MDYyLWE0NjQtNThhYzcwNDg1OWVlIiwiaWFtX2lkIjoiaWFtLVNlcnZpY2VJZC1lOTljOTk3ZS1lNzk3LTQwNjItYTQ2NC01OGFjNzA0ODU5ZWUiLCJzdWJfdHlwZSI6IlNlcnZpY2VJZCIsIm5hbWUiOiJjb3MtYXBpLWtleSJ9LCJhY2NvdW50Ijp7ImJvdW5kYXJ5IjoiZ2xvYmFsIiwidmFsaWQiOnRydWUsImJzcyI6ImIxMmExYTRiNzljODRmMTlhYzJiMmY4OGQ3OWI2MjY0IiwiZnJvemVuIjp0cnVlfSwiaWF0IjoxNjM4MDA5ODcxLCJleHAiOjE2MzgwMTM0NzEsImlzcyI6Imh0dHBzOi8vaWFtLmNsb3VkLmlibS5jb20vaWRlbnRpdHkiLCJncmFudF90eXBlIjoidXJuOmlibTpwYXJhbXM6b2F1dGg6Z3JhbnQtdHlwZTphcGlrZXkiLCJzY29wZSI6ImlibSBvcGVuaWQiLCJjbGllbnRfaWQiOiJkZWZhdWx0IiwiYWNyIjoxLCJhbXIiOlsicHdkIl19.KJdb9aKusD_vqmPOzBSfarlPLjO4ol6A4gwbcZyj9VsHAApG_j0ucNGt0KfxrMZmOhjiwDPQwc_SnbnLpvenq5D-MUzCtzdpeqg3IJRFmRFDGrsiu2mcWAD3ScIzLmXTuE4zVKtmWpND2T6JkG4JP3Wnvn4qwZvZaAlb830ZP6w9zmDEVpCG3p_7RlrzF6mLIBbU9RsOgvjstjurR-ESQCwKnby2h6YeAHGPvENxbNateBvQozQ0bLiJ69newhRuPCpU9gmSPvlto38GDpYGR2CPv87beJlVD3l_P-umqN3t0odV15o_L-ms47AvQ-7aS0w8SSv2USRxcvDz9R-jzQ","refresh_token":"not_supported","token_type":"Bearer","expires_in":3600,"expiration":1638013471,"scope":"ibm openid"}
    "}
---

**Comment by rgowrishankar** [comment]
PR: https://github.com/razee-io/RemoteResourceS3/pull/282
